In [29]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [30]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [31]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
      nn.Linear(28*28, 512),
      nn.ReLU(),
      nn.Linear(512, 512),
      nn.ReLU(),
      nn.Linear(512, 10),
    )

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

In [32]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [33]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")
print(pred_probab)

Predicted class: tensor([1])
tensor([[0.0973, 0.1111, 0.0998, 0.1039, 0.0982, 0.0957, 0.0878, 0.1027, 0.0966,
         0.1069]], grad_fn=<SoftmaxBackward0>)


In [34]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [35]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [36]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [37]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.2158,  0.0508,  0.2385, -0.1959,  0.2710,  0.2571, -0.2471,  0.1529,
          0.1734, -0.5495, -0.2208, -0.0628,  0.0655, -0.0547,  0.3686,  0.4613,
          0.0224, -0.1576,  0.6343,  0.1038],
        [-0.3531,  0.0979,  0.0705, -0.0373,  0.4563,  0.5822, -0.1016, -0.2588,
          0.1524, -0.3008, -0.2322,  0.0818, -0.1929,  0.4121,  0.4365,  0.4762,
          0.0985, -0.0547,  0.5517, -0.1527],
        [-0.0061,  0.3281,  0.0428, -0.3664,  0.0629,  0.3630, -0.1606,  0.3459,
          0.1726, -0.5408,  0.1398,  0.0812, -0.0529,  0.1395,  0.1073,  0.5398,
         -0.1323, -0.0352,  0.5854, -0.0957]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0508, 0.2385, 0.0000, 0.2710, 0.2571, 0.0000, 0.1529, 0.1734,
         0.0000, 0.0000, 0.0000, 0.0655, 0.0000, 0.3686, 0.4613, 0.0224, 0.0000,
         0.6343, 0.1038],
        [0.0000, 0.0979, 0.0705, 0.0000, 0.4563, 0.5822, 0.0000, 0.0000, 0.1524,
         0.0000, 0.0000, 0.0818, 0.0000, 0.4121, 0.43

In [38]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
print(logits)

tensor([[ 0.4075, -0.1191, -0.1866,  0.0624, -0.1489,  0.2055, -0.0267,  0.0617,
          0.1190, -0.0595],
        [ 0.3127, -0.1167, -0.2035,  0.2492, -0.1414,  0.1365, -0.0424,  0.0129,
          0.0839, -0.1629],
        [ 0.3089, -0.1125, -0.1735,  0.0512, -0.1352,  0.2316, -0.0978, -0.0611,
          0.0280, -0.0570]], grad_fn=<AddmmBackward0>)


In [39]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
print(pred_probab)

tensor([[0.1434, 0.0847, 0.0792, 0.1016, 0.0822, 0.1172, 0.0929, 0.1015, 0.1075,
         0.0899],
        [0.1330, 0.0866, 0.0794, 0.1248, 0.0845, 0.1115, 0.0933, 0.0986, 0.1058,
         0.0827],
        [0.1348, 0.0884, 0.0832, 0.1042, 0.0865, 0.1248, 0.0898, 0.0931, 0.1018,
         0.0935]], grad_fn=<SoftmaxBackward0>)


In [40]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0310, -0.0148, -0.0046,  ...,  0.0076,  0.0345,  0.0002],
        [ 0.0092,  0.0260, -0.0242,  ..., -0.0144,  0.0128, -0.0115]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([ 0.0142, -0.0339], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0152, -0.0399, -0.0366,  ..., -0.0271,  0.0048,  0.0320],
        [ 0.0248,  0.0409,  0.0215,  ...,  0.0241, -0.0027, -0.0281]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 